parent=keycloak.v2
styles=css/poc.css css/pattaya-login.css
pocAppBaseUrl=http://localhost:8000
pocLoginUrl=http://localhost:8000/oauth2/start?rd=http%3A%2F%2Flocalhost%3A8000%2F
pocUpdateEmailUrl=http://localhost:8000/oauth2/start?rd=http%3A%2F%2Flocalhost%3A8000%2F&kc_action=UPDATE_EMAIL
