parent=keycloak.v2
styles=css/poc.css css/pattaya-login.css
pocAppBaseUrl=https://pfas-playground.local.pitsdev.com
pocLoginUrl=https://pfas-playground.local.pitsdev.com/oauth2/start?rd=https%3A%2F%2Fpfas-playground.local.pitsdev.com%2F
pocUpdateEmailUrl=https://pfas-playground.local.pitsdev.com/oauth2/start?rd=https%3A%2F%2Fpfas-playground.local.pitsdev.com%2F&kc_action=UPDATE_EMAIL
